site_name: Florida Health Charts Web Scraper
nav:
  - Home: index.md
  - API Reference: api_reference.md
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")
      watch:
        - src/fl_health_scraper
